POST http://localhost:5000/customers
Content-Type: application/json

{
    "customer_name": "Nguyễn Văn Nam",
    "customer_email": "nguyenvanam@gmail.com",
    "customer_number_phone": "0979008305",
    "is_deleted": 0
}

###
POST http://localhost:5000/customers/search
Content-Type: application/json

{
    "customer_name": "",
    "customer_email": "",
    "customer_number_phone": ""
}

###
GET http://localhost:5000/customers/2

###
PUT http://localhost:5000/customers/2
Content-Type: application/json

{
    "customer_name": "Nguyễn Văn Nam",
    "customer_email": "nguyenvanam@gmail.com",
    "customer_number_phone": "0979008305"
}

###
DELETE  http://localhost:5000/customers/2
